### ISSUE TITLE
Light verb constructions

### ISSUE THREAD

**Issue by sylvainkahane** [surfacesyntacticud/website#5]
In SUD_Fench-Spoken the complement of the lvc is attached to the noun, while in SUD_French-Spoken it attached  to the light verb. I really think that it is better to attach it the noun because

1. the noun can form a phrase with the complement : "le projectile a tendance à se mettre en travers" [ex 00157](http://match.grew.fr/?corpus=SUD_French-GSD@latest&custom=5edb3dc0832e2) -> "cette tendance à se mettre en travers doit être rectifiée"

2. it's the noun that is the predicate and controls the valency. In the previous example, HAVE is binary predicate, not a ternary predicate.

Moreover, in UD, the complement is also attached to the noun. Cf. [this discussion](https://github.com/UniversalDependencies/docs/issues/687) for instance.

**Comment by perrier54** [comment]
I agree with this analysis and I will modify the annotation of the [SUD_French-GSD](https://github.com/surfacesyntacticud/SUD_French-GSD) corpus in this sense.

**Comment by kimgerdes** [comment]
i agree that it's better in general, but there are cases where noun and other complement don't really form a unit:
```
il se rend compte du climat
*compte du climat
```
idem: `il doit prendre garde à ne pas toucher la veste, ils ont beau être en rupture de stock, ça donne lieu à un travail remarquable, ça a lieu demain, il a donné raison à sa fille, ...`

i would estimate that this concerns a quarter to a third of the lvcs in french. but the general rule could still be to attach to the noun of course.

there could even be a general rule: if you can't decide, attach low, like in my favorite example `il a fait le constat d'une montée du nationalisme en catalogne` where it seems as if you could attache "en catalogne" just about everywhere.

btw, I stumbled upon this in gsd:
`il n'y avait pas d'après la Bible de lieux de culte permanents et fixes.`
this is not lvc i'd say.

**Comment by bguil** [comment]
I agree with @sylvainkahane to attach the complement to the `NOUN`.
But I guess that the VERB was chosen to have a more regular analysis in term of relation.
It's sensible to have a `comp:obl` relation for the complement and it is usually annotated [this way](http://match.grew.fr/?corpus=SUD_French-GSD@latest&custom=5ee075cf94444).
Attaching a `comp:obl` relation to a `NOUN` is quite [uncommon](http://match.grew.fr/?corpus=SUD_French-GSD@latest&custom=5ee076183118c).

**Comment by sylvainkahane** [comment]
It is not absolutely clear for me that we need to annotate verbal idioms such as _prendre  garde_.

Nevertheless, I see two options if do it:

1. we use `@fixed` but it  must be clear that in this case the relation is not converted into `fixed` in UD, for instance because `EXTPOS=VERB`.

2. we introduce another feature, for instance `@idiom`, for idioms that we do not want to convert into `fixed` in UD.

Note that it concerns also example such as _se souvenir_ where the relation between _souvenir_ and _se_ must be annotated `comp@fixed` or `comp@idiom`.

**Comment by bguil** [comment]
In the PARSEME-FR project, the two constructions are also annotated differently:

 * with label `VID` for *avoir lieu*,  *prendre part*… ([examples](http://match.grew.fr/?corpus=sequoia.surf.parseme@master&custom=5ee1d2a637d50))
 * with label `LVC.full` for *avoir conscience*, *rendre service*… ([examples](http://match.grew.fr/?corpus=sequoia.surf.parseme@master&custom=5ee1d1fda2a1d))

I prefer to use `@idiom` in SUD annotation. This improves the fact that, when SUD used the UD terminology (`fixed` in this case), it is with the same scope.

**Comment by kimgerdes** [comment]
thanks for the links. it's the first time i really looked at the parseme results.

i agree that we could propose the @idiom relation but i don't see us putting this information on the data anytime soon where it isn't already thanks to parseme.

even the examples VID in the parseme link above don't seem to obey to the same rules that we discussed. for example `laisser le soin à qqn` looks more like an lvc to me. idem `avoir le tort de, avoir l'occasion de, adoucir les moeurs, donner signe de vie, prendre ses responsabilités ...`

there may even be cases where the idiom seems to consist of two parts, and this idiom can exist without the verb, so that it looks more like a support verb of an idiom: `la main à la pâte, le dos au public, ...`

most of the times the object has a determiner, it seems that they can form a phrase by themselves, which was the first criterion given by @sylvainkahane for proposing the special, verb-like, low attachment of the argument.

**Comment by perrier54** [comment]
In my opinion, it is not necessary to make a specific annotation of the idioms. They are specific MWEs and they are annotated like all MWEs. I refer to my proposal (#4) to annotate MWEs. 

And some idioms may contain light verbs. For example, consider the expression `"donner signe de vie"`. If we consider it as an idiom with the light verb `"donner"`, we have the following annotation.

> `donner[upos=VERB, ExtPos=VERB,Type=MWE] -[comp:obj@lvc]-> signe[upos=NOUN, InMWE=Yes] -[mod]-> de[upos=ADP, InMWE=Yes] -[comp:obj]-> vie[upos=NOUN, InMWE=Yes]`

My proposal for the annotation of MWEs has the advantage that discontinuous MWEs are annotated without problems, whereas the UD `fixed` relation  imposes continuity.
For example: `il ne donne pas signe de vie`

**Comment by kimgerdes** [comment]
I like the analysis of this sentence.
maybe instead of InMWE=Yes we could give the MWE type instead?
Two questions remain:
1. How difficult do you think it is to put this information more systematicaly on all french treebanks?
2. Will you write the MWE page of the sud guidelines, Guy?

**Comment by sylvainkahane** [comment]
In my terminology, LVCs and idioms are different constructions. I don't think we need to put a feature `Type=MWE` on LVCs.

About _laisser le soin a qqn de Vinf_, it's a causative support verb construction (cf. _prendre le soin de Vinf_, which is the corresponding LVC). According to MTT, both constructions are considered as collocations and should be analyzeed in a similar way. The term LVC is too restrictive because it applies only to light verb, that is meaningless, and cannot easily be extended to other verbal collocations. Parseme decided to encode only LVC and to merge other collocations with idioms, which is an error to my point of view. UD followed with the extension `:lvc`.

Considering only the syntactic point of view, I think that all collocations should be annotated in the same way. I propose to extend the feature `@lvc` to other verbal collocations.

About the feature `@idiom`, it is totally optional. Let us see if we need to use it or not. In any case we  will suppress it in the SUD>UD conversion.

**Comment by perrier54** [comment]
I reviewed all constructions with light verbs in [`SUD_French-GSD`](https://github.com/surfacesyntacticud/SUD_French-GSD) and concluded that there are two kinds of constructions:

- In some constructions, the complement of the expression `(light verb + object)` is attached to the object (`"avoir peur de qqchose (be afraid of something)"`
- In the others , the complement is attached to the verb (`" rendre compte à quelqu'un (report to someone)"`

**Comment by kimgerdes** [comment]
Hello,
Having talked with @MariamNakhle earlier today, we wonder what action on her part you recommend now concerning the lexicon harmonization across French treebanks.
Should she
- extract all the couples of words connected by lvc? - in order to apply this to the other treebanks if the same couple arises?
- extract all the nominal objects that do not have a determiner in a special list that we look at in order to decide whether we have something idiomatic?
- forget about lvc in the lexicon? - that would mean that only GSD will have that information, unless I'm mistaken.
Any other idea about harmonization concerning idioms?

**Comment by perrier54** [comment]
I agree with @kimgerdes on his first two proposals. Concerning the first proposal, maybe we should first agree on the class of pairs _(light verb, complement)_ extracted from [SUD_French-GSD](https://github.com/surfacesyntacticud/SUD_French-GSD): external complements attached to the verb or to the linked complement.

Concerning the second proposal , here is a [GREW](http://grew.fr/) request doing the work:

> `pattern{A[upos=VERB]; A -[1=comp,2=obj|obl]-> B; B[upos=NOUN]}
without{B -[det]-> *}
without{A -[deep=lvc]-> B}`

**Comment by perrier54** [comment]
**Decision** : the complement of a `( VERB -[comp:obj@lvc]-> OBJ)` construction is attached to OBJ if it can be considered independently of VERB, otherwise it is attached to VERB.

Examples : _j'ai peur de mourir_  (I'm afraid to die) - _la peur de mourir me hante_ (the fear of dying haunts me)
peur -[comp:obl]-> de

Je me rends compte de mon erreur (I realize my mistake )
rends -[comp:obl]-> de

**Correction of the treebanks:**
- [ ] GSD
- [ ] Rhaposodie
- [ ] Paris Stories
